on: [push]
jobs:
  build_and_analysis:
    runs-on: ubuntu-latest
    container:
      image: artfulbytes/msp430-gcc-9.3.1.11:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make
      - run: make cppcheck
